run:
	go run ./cmd/
run-example:
	go run ./cmd/ examples/example.forth	
build:
	go build -o forth ./cmd/
lint:
	gocritic check ./...
	revive ./...
	golint ./...
	go vet ./...
	goconst ./...
test:
	go test ./...
